export const metadata = {
  title: "Sign In",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function SignInLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="grid h-screen place-items-center">{children}</div>;
}
